pipeline:
  name: DataIngestor deploy
  identifier: DataIngestor_deploy
  orgIdentifier: default
  projectIdentifier: UCDHarnessRG
  tags:
    language: python
  stages:
  - stage:
      name: dataloader-service
      identifier: dataloader_service
      type: Deployment
      spec:
        deploymentType: CustomDeployment
        service:
          serviceRef: DataIngestor_dataloader_service
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
  - stage:
      name: datapipe-cli
      identifier: datapipe_cli
      type: Deployment
      spec:
        deploymentType: CustomDeployment
        service:
          serviceRef: DataIngestor_datapipe_cli
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
