service:
  name: Windows_Web_Application_Test_Deployments_Windows_Service
  identifier: Windows_Batch_Test_Deployments_Windows_Web_Application_Test_Deployments_Windows_Service
  tags:
    Windows_Service: 'true'
  serviceDefinition:
    type: Custom
    spec:
      variables: []
  orgIdentifier: default
  projectIdentifier: UCDHarnessRG
