pipeline:
  name: OrderOps deploy
  identifier: OrderOps_deploy
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    runtime: dotnet
  stages:
  - stage:
      name: Deploy orderops-web
      identifier: Deploy_orderops_web
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: OrderOps_orderops_web
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
  - stage:
      name: Deploy orderops-worker
      identifier: Deploy_orderops_worker
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: OrderOps_orderops_worker
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
  - stage:
      name: Deploy orderops-agent
      identifier: Deploy_orderops_agent
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: OrderOps_orderops_agent
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
  - stage:
      name: Deploy orderops-config
      identifier: Deploy_orderops_config
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: OrderOps_orderops_config
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
