service:
  name: Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test
  identifier: Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    Ext_Script: 'true'
    Windows-BATCH: 'true'
  serviceDefinition:
    type: WinRm
    spec: {}
