pipeline:
  name: DataIngestor deploy
  identifier: DataIngestor_deploy
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    language: python
  stages:
  - stage:
      name: Deploy dataloader-service
      identifier: Deploy_dataloader_service
      type: Deployment
      spec:
        deploymentType: Custom
        service:
          serviceRef: DataIngestor_dataloader_service
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
  - stage:
      name: Deploy datapipe-cli
      identifier: Deploy_datapipe_cli
      type: Deployment
      spec:
        deploymentType: Custom
        service:
          serviceRef: DataIngestor_datapipe_cli
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
