pipeline:
  name: Javahosting Nitro Application Test Deployments deploy
  identifier: Javahosting_Nitro_Application_Test_Deployments_deploy
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    bsa: Developer Experience and Platform
    org: Infrastructure and Operations
    appId: '8006'
    regulated: 'false'
    ci_name: Concourse CI
    criticality: critical
  stages:
  - stage:
      name: Deploy Javahosting_Nitro_Application_Test_Deployments_Properties
      identifier: Deploy_Javahosting_Nitro_Application_Test_Deployments_Properties
      type: Deployment
      spec:
        deploymentType: Custom
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_Javahosting_Nitro_Application_Test_Deployments_Properties
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
  - stage:
      name: Deploy Javahosting_Nitro_Application_Test_Deployments_WAR
      identifier: Deploy_Javahosting_Nitro_Application_Test_Deployments_WAR
      type: Deployment
      spec:
        deploymentType: Custom
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_Javahosting_Nitro_Application_Test_Deployments_WAR
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
  - stage:
      name: Deploy Javahosting_Nitro_Application_Test_Deployments_Web_Content
      identifier: Deploy_Javahosting_Nitro_Application_Test_Deployments_Web_Content
      type: Deployment
      spec:
        deploymentType: Custom
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_Javahosting_Nitro_Application_Test_Deployments_Web_Content
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
  - stage:
      name: Deploy Javahosting_Nitro_Application_Test_Deployments_zero_downtime
      identifier: Deploy_Javahosting_Nitro_Application_Test_Deployments_zero_downtime
      type: Deployment
      spec:
        deploymentType: Custom
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_Javahosting_Nitro_Application_Test_Deployments_zero_downtime
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
