pipeline:
  name: Windows Web Application Test Deployments - deploy
  identifier: Windows_Web_Application_Test_Deployments_deploy
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags: {}
  stages:
  - stage:
      name: PH37507_test
      identifier: PH37507_test
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: PH37507_test
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      PH37507_test"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_COM
      identifier: Windows_Web_Application_Test_Deployments_COM
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_COM
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_COM"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_App
      identifier: Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_App
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_App
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_App"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_Proxy
      identifier: Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_Proxy
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_Proxy
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_UCD_COM_MSI_Test_Proxy"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_UCD_IIS_App_Restart_Test
      identifier: Windows_Web_Application_Test_Deployments_UCD_IIS_App_Restart_Test
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_UCD_IIS_App_Restart_Test
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_UCD_IIS_App_Restart_Test"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_UCD_IIS_Site_Restart_Test
      identifier: Windows_Web_Application_Test_Deployments_UCD_IIS_Site_Restart_Test
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_UCD_IIS_Site_Restart_Test
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_UCD_IIS_Site_Restart_Test"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test
      identifier: Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_UCD_Windows_Config_Test
      identifier: Windows_Web_Application_Test_Deployments_UCD_Windows_Config_Test
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_UCD_Windows_Config_Test
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_UCD_Windows_Config_Test"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_UCD_Windows_Web_App_Test
      identifier: Windows_Web_Application_Test_Deployments_UCD_Windows_Web_App_Test
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_UCD_Windows_Web_App_Test
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_UCD_Windows_Web_App_Test"'
  - stage:
      name: Windows_Web_Application_Test_Deployments_Windows_Service
      identifier: Windows_Web_Application_Test_Deployments_Windows_Service
      type: Deployment
      spec:
        deploymentType: WinRm
        service:
          serviceRef: Windows_Web_Application_Test_Deployments_Windows_Service
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: PowerShell
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'Write-Host "TODO: implement deployment for component:
                      Windows_Web_Application_Test_Deployments_Windows_Service"'
