service:
  name: orderops-config
  identifier: OrderOps_orderops_config
  tags:
    runtime: dotnet
    Windows_Config_Deploy: 'true'
  serviceDefinition:
    type: Custom
    spec:
      variables: []
  orgIdentifier: my_org
  projectIdentifier: my_project
