service:
  name: orderops-config
  identifier: orderops_config
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    Windows_Config_Deploy: 'true'
  serviceDefinition:
    type: WinRm
    spec: {}
