service:
  name: 1930_DPS_Deploy_Multiple_Deployment_Groups
  identifier: Informatica_PowerCenter_1930_DPS_Deploy_Multiple_Deployment_Groups
  tags:
    bsa: Enterprise Data Office
    org: Technology Enterprise Solutions
    ci_name: Informatica PowerCenter
    appId: '1930'
    criticality: critical
    regulated: 'true'
    Informatica_Multiple_Deployment_Group: 'true'
  serviceDefinition:
    type: Custom
    spec:
      variables: []
  orgIdentifier: default
  projectIdentifier: UCDHarnessRG
