service:
  name: Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test
  identifier: Windows_Application_Standard_Test_Deployments_Windows_Web_Application_Test_Deployments_UCD_Windows_Application_Batch_Test
  tags:
    bsa: Developer Experience and Platform
    org: Infrastructure and Operations
    appId: '8878'
    criticality: not_critical
    regulated: 'false'
    ci_name: GitHub Organization Probots
    Ext_Script: 'true'
    Windows-BATCH: 'true'
  serviceDefinition:
    type: Custom
    spec:
      variables: []
  orgIdentifier: my_org
  projectIdentifier: my_project
