pipeline:
  name: CustomerPortal deploy
  identifier: CustomerPortal_deploy
  orgIdentifier: default
  projectIdentifier: UCDHarnessRG
  tags:
    bsa: Customer Solutions
    language: java
    build: gradle
  stages:
  - stage:
      name: customerportal-api
      identifier: customerportal_api
      type: Deployment
      spec:
        deploymentType: CustomDeployment
        service:
          serviceRef: CustomerPortal_customerportal_api
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
  - stage:
      name: customerportal-batch
      identifier: customerportal_batch
      type: Deployment
      spec:
        deploymentType: CustomDeployment
        service:
          serviceRef: CustomerPortal_customerportal_batch
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
  - stage:
      name: customerportal-web
      identifier: customerportal_web
      type: Deployment
      spec:
        deploymentType: CustomDeployment
        service:
          serviceRef: CustomerPortal_customerportal_web
        environment:
          environmentRef: <+input>
          deployToAll: true
          infrastructureDefinitions:
          - identifier: input
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo TODO: implement deployment'
      failureStrategies:
      - onFailure:
          errors:
          - AllErrors
          action:
            type: StageRollback
