pipeline:
  name: Javahosting Nitro Application Test Deployments - deploy
  identifier: Javahosting_Nitro_Application_Test_Deployments_deploy
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    bsa: Developer Experience and Platform
    org: Infrastructure and Operations
    appId: '8006'
    regulated: 'false'
    ci_name: Concourse CI
    criticality: critical
  stages:
  - stage:
      name: Javahosting_Nitro_Application_Test_Deployments_Properties
      identifier: Javahosting_Nitro_Application_Test_Deployments_Properties
      type: Deployment
      spec:
        deploymentType: Ssh
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_Properties
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo "TODO: implement deployment for component: Javahosting_Nitro_Application_Test_Deployments_Properties"'
  - stage:
      name: Javahosting_Nitro_Application_Test_Deployments_WAR
      identifier: Javahosting_Nitro_Application_Test_Deployments_WAR
      type: Deployment
      spec:
        deploymentType: Ssh
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_WAR
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo "TODO: implement deployment for component: Javahosting_Nitro_Application_Test_Deployments_WAR"'
  - stage:
      name: Javahosting_Nitro_Application_Test_Deployments_Web_Content
      identifier: Javahosting_Nitro_Application_Test_Deployments_Web_Content
      type: Deployment
      spec:
        deploymentType: Ssh
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_Web_Content
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo "TODO: implement deployment for component: Javahosting_Nitro_Application_Test_Deployments_Web_Content"'
  - stage:
      name: Javahosting_Nitro_Application_Test_Deployments_zero_downtime
      identifier: Javahosting_Nitro_Application_Test_Deployments_zero_downtime
      type: Deployment
      spec:
        deploymentType: Ssh
        service:
          serviceRef: Javahosting_Nitro_Application_Test_Deployments_zero_downtime
        environment:
          environmentRef: <+input>
          infrastructureDefinitions:
          - identifier: <+input>
        execution:
          steps:
          - step:
              name: Deploy
              identifier: Deploy
              type: ShellScript
              spec:
                shell: Bash
                onDelegate: true
                source:
                  type: Inline
                  spec:
                    script: 'echo "TODO: implement deployment for component: Javahosting_Nitro_Application_Test_Deployments_zero_downtime"'
