pipeline:
  name: WebApp-Deployment
  identifier: WebApp_Deployment
  projectIdentifier: my_project
  orgIdentifier: my_org
  tags: { deploy: "webapp" }
  stages:
    - stage:
        name: Deploy WebApp
        identifier: Deploy_WebApp
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: WebAppService
          environment:
            environmentRef: dev
            deployToAll: true
          execution:
            steps:
              - step:
                  name: Stop Web Server
                  identifier: Stop_Web_Server
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          systemctl stop tomcat
              - step:
                  name: Copy Artifacts
                  identifier: Copy_Artifacts
                  type: DownloadArtifact
                  spec:
                    connectorRef: artifact_repo
                    artifactRef: WebAppArtifact
                    destinationPath: /opt/tomcat/webapps
              - step:
                  name: Start Web Server
                  identifier: Start_Web_Server
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          systemctl start tomcat
